# Generated by Django 5.0.2 on 2024-02-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0003_courses_deliverables_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='deliverables',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Deliverables'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Teachers'},
        ),
    ]
